### ISSUE TITLE
Proceso de negocio Mejorado

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-mejorado-equipo-s-b-j#2]
[PROCESO DE NEGOCIO MEJORADO.pdf](https://github.com/user-attachments/files/17263640/PROCESO.DE.NEGOCIO.MEJORADO.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Muy bien compañeros, 20% de 20% en base a la rúbrica

**Comment by Daisy-GonzalezLita12** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
